// src/types/model-viewer.d.ts
// This file declares the custom <model-viewer> element for TypeScript.

declare namespace JSX {
  interface IntrinsicElements {
    "model-viewer": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
      src: string;
      alt?: string;
      "auto-rotate"?: boolean;
      "camera-controls"?: boolean;
      "ar"?: boolean;
      "ar-modes"?: string;
      "shadow-intensity"?: string;
      "camera-orbit"?: string;
      "field-of-view"?: string;
      "exposure"?: string;
      "skybox-image"?: string;
      "environment-image"?: string;
      "poster"?: string;
      "loading"?: "eager" | "lazy";
      "reveal"?: "auto" | "interaction" | "manual";
      "interaction-prompt"?: "auto" | "none" | "dot" | "ring";
      "interaction-prompt-threshold"?: string;
      "interaction-prompt-variant"?: "dot" | "ring";
      "disable-zoom"?: boolean;
      "disable-pan"?: boolean;
      "disable-tap"?: boolean;
      "min-camera-orbit"?: string;
      "max-camera-orbit"?: string;
      "min-field-of-view"?: string;
      "max-field-of-view"?: string;
      "interpolation-decay"?: string;
      "orbit-sensitivity"?: string;
      "pan-sensitivity"?: string;
      "touch-action"?: string;
      "variant"?: "none" | "albedo" | "metallic-roughness" | "normal" | "occlusion" | "emissive";
      "tone-mapping"?: "none" | "linear" | "aces" | "agx";
      "shadow-softness"?: string;
      "camera-target"?: string;
      "animation-name"?: string;
      "animation-crossfade-duration"?: string;
      "autoplay"?: boolean;
      "loop"?: boolean;
      "orientation"?: string;
      "scale"?: string;
      "rotation"?: string;
      "position"?: string;
      "bounds"?: string;
      "max-lights"?: string;
      "min-lights"?: string;
      "max-shadow-distance"?: string;
      "min-shadow-distance"?: string;
      "shadow-map-size"?: string;
      "shadow-bias"?: string;
      "shadow-normal-bias"?: string;
      "shadow-cascade-count"?: string;
      "shadow-cascade-splits"?: string;
      "shadow-cascade-far-splits"?: string;
      "shadow-cascade-near-splits"?: string;
      "shadow-cascade-resolution"?: string;
      "shadow-cascade-max-distance"?: string;
      "shadow-cascade-min-distance"?: string;
      "shadow-cascade-fade-range"?: string;
      "shadow-cascade-blend-factor"?: string;
      "shadow-cascade-debug"?: boolean;
      "shadow-cascade-debug-color"?: string;
      "shadow-cascade-debug-opacity"?: string;
      "shadow-cascade-debug-wireframe"?: boolean;
      "shadow-cascade-debug-wireframe-color"?: string;
      "shadow-cascade-debug-wireframe-opacity"?: string;
      "shadow-cascade-debug-wireframe-width"?: string;
      "shadow-cascade-debug-wireframe-depth"?: string;
      "shadow-cascade-debug-wireframe-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-factor"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-units"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-scale"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-bias"?: string;
      "shadow-cascade-debug-wireframe-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias-offset-normal-bias"?: string;
    };
  }
}