/// <reference types="vite/client" />

declare namespace JSX {
  interface IntrinsicElements {
    "model-viewer": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
      src?: string;
      alt?: string;
      "auto-rotate"?: boolean;
      "camera-controls"?: boolean;
      "ar"?: boolean;
      "ar-modes"?: string;
      "ar-scale"?: string;
      "shadow-intensity"?: string;
      "environment-image"?: string;
      "poster"?: string;
      "seamless-poster"?: boolean;
      "reveal"?: string;
      "loading"?: string;
      "camera-orbit"?: string;
      "field-of-view"?: string;
      "min-camera-orbit"?: string;
      "max-camera-orbit"?: string;
      "min-field-of-view"?: string;
      "max-field-of-view"?: string;
      "interaction-prompt"?: string;
      "interaction-prompt-threshold"?: string;
      "interaction-prompt-style"?: string;
      "skybox-image"?: string;
      "exposure"?: string;
      "shadow-softness"?: string;
      "disable-zoom"?: boolean;
      "disable-pan"?: boolean;
      "disable-rotate"?: boolean;
      "animation-name"?: string;
      "variant-name"?: string;
      "autoplay"?: boolean;
      "camera-target"?: string;
      "orientation"?: string;
      "interpolation-decay"?: string;
      "max-field-of-view"?: string;
      "min-field-of-view"?: string;
      "max-camera-orbit"?: string;
      "min-camera-orbit"?: string;
      "max-focal-length"?: string;
      "min-focal-length"?: string;
      "max-aspect-ratio"?: string;
      "min-aspect-ratio"?: string;
      "scale"?: string;
      "rotation-per-second"?: string;
      "touch-action"?: string;
      "onLoad"?: (event: Event) => void;
      "onCameraChange"?: (event: Event) => void;
      "onModelVisibility"?: (event: Event) => void;
      "onProgress"?: (event: Event) => void;
      "onResize"?: (event: Event) => void;
      "onSceneGraphUpdate"?: (event: Event) => void;
      "onVariantApplied"?: (event: Event) => void;
      "onArTracking"?: (event: Event) => void;
      "onArPlacement"?: (event: Event) => void;
      "onArDismissed"?: (event: Event) => void;
      "onArTrackingLost"?: (event: Event) => void;
      "onArTrackingRestored"?: (event: Event) => void;
      "onArTrackingStarted"?: (event: Event) => void;
      "onArTrackingStopped"?: (event: Event) => void;
      "onArTrackingError"?: (event: Event) => void;
      "onArTrackingUnsupported"?: (event: Event) => void;
      "onArTrackingNotAllowed"?: (event: Event) => void;
      "onArTrackingNotAvailable"?: (event: Event) => void;
      "onArTrackingNotSupported"?: (event: Event) => void;
      "onArTrackingNotEnabled"?: (event: Event) => void;
      "onArTrackingNotConfigured"?: (event: Event) => void;
      "onArTrackingNotInitialized"?: (event: Event) => void;
      "onArTrackingNotStarted"?: (event: Event) => void;
      "onArTrackingNotStopped"?: (event: Event) => void;
      "onArTrackingNotDismissed"?: (event: Event) => void;
      "onArTrackingNotPlaced"?: (event: Event) => void;
      "onArTrackingNotResumed"?: (event: Event) => void;
      "onArTrackingNotPaused"?: (event: Event) => void;
      "onArTrackingNotReset"?: (event: Event) => void;
      "onArTrackingNotUpdated"?: (event: Event) => void;
      "onArTrackingNotRemoved"?: (event: Event) => void;
      "onArTrackingNotAdded"?: (event: Event) => void;
      "onArTrackingNotSelected"?: (event: Event) => void;
      "onArTrackingNotDeselected"?: (event: Event) => void;
      "onArTrackingNotFocused"?: (event: Event) => void;
      "onArTrackingNotBlurred"?: (event: Event) => void;
      "onArTrackingNotActivated"?: (event: Event) => void;
      "onArTrackingNotDeactivated"?: (event: Event) => void;
      "onArTrackingNotEnabledChanged"?: (event: Event) => void;
      "onArTrackingNotAvailableChanged"?: (event: Event) => void;
      "onArTrackingNotSupportedChanged"?: (event: Event) => void;
      "onArTrackingNotConfiguredChanged"?: (event: Event) => void;
      "onArTrackingNotInitializedChanged"?: (event: Event) => void;
      "onArTrackingNotStartedChanged"?: (event: Event) => void;
      "onArTrackingNotStoppedChanged"?: (event: Event) => void;
      "onArTrackingNotDismissedChanged"?: (event: Event) => void;
      "onArTrackingNotPlacedChanged"?: (event: Event) => void;
      "onArTrackingNotResumedChanged"?: (event: Event) => void;
      "onArTrackingNotPausedChanged"?: (event: Event) => void;
      "onArTrackingNotResetChanged"?: (event: Event) => void;
      "onArTrackingNotUpdatedChanged"?: (event: Event) => void;
      "onArTrackingNotRemovedChanged"?: (event: Event) => void;
      "onArTrackingNotAddedChanged"?: (event: Event) => void;
      "onArTrackingNotSelectedChanged"?: (event: Event) => void;
      "onArTrackingNotDeselectedChanged"?: (event: Event) => void;
      "onArTrackingNotFocusedChanged"?: (event: Event) => void;
      "onArTrackingNotBlurredChanged"?: (event: Event) => void;
      "onArTrackingNotActivatedChanged"?: (event: Event) => void;
      "onArTrackingNotDeactivatedChanged"?: (event: Event) => void;
    };
  }
}